---
#-------------------------------
# General Site Settings

title: NeuroGEARS
logo: /assets/images/neurogears.svg
author: themefisher
description: Neuroscience, Games, Interaction, Robotics
email: contact@neurogears.org
phone:
location: NeuroGEARS Ltd is a limited company registered in England and Wales. <br/>31 Oval Road, London, NW1 7EA, United Kingdom <br/>Company Registration No. 10773335
copyright: <span class="paragraph-copyright">© 2021 NeuroGEARS Ltd. <br/><br/>Website built on Kross jekyll Creative Portfolio Template (2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com))</span>

menu:
  - { name: About Us, link: "/about" }
  - { name: News, link: "/news" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-106624760-1

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: <span class="h1black">neurogears</span> is a creative research <br> group bridging <span class="h1color">Neuroscience</span>, <br> <span class="h1color">Games</span>, <span class="h1color">Interaction</span> & <span class="h1color">Robotics</span>.

social:
  - { icon: "ti-github", link: "https://github.com/neurogears" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-youtube", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: We engage with top research and academic institutions worldwide to reimagine science by using and creating open-source tools which are accessible, understandable and modifiable. Our core mission is to make scientific knowledge available to everyone, and to empower people to follow their curiosity, wherever it may lead.

blurb-btn-link: "/about"
blurb-btn-name: learn more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "In this first stage, we need to develop a solid understanding of what the experience should be for our clients and their audiences."

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Next, we help our clients shape their long-term vision and identify short-term project goals and strategic objectives. With a shared goal in mind, we can now easily build a map for how to get us there."

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "We collaboratively decide on a process for regularly releasing functional prototypes and tracking our progress towards goals. We want to keep our clients in the loop and get their feedback on an ongoing basis throughout the entire project, not just at milestone meetings."

# Team Section
team:
  - title: "Gonçalo Lopes"
    image: "assets/images/team/glopes.jpg"
    designation: "Director"

  - title: "André Almeida"
    image: "assets/images/team/aalmeida.jpg"
    designation: "Senior Software Engineer"

  - title: "Danbee Kim"
    image: "assets/images/team/dkim.jpg"
    designation: "Research and Outreach Scientist"

  - title: "Joana Nogueira"
    image: "assets/images/team/missing-team-member-photo.png"
    designation: "Executive Assistant"

  - title: "Bruno Cruz"
    image: "assets/images/team/bcruz.png"
    designation: "Software Engineer"

#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: Open Source Research <br/>and Development,
      icon: ti-mouse,
      description: "NeuroGEARS employs the core team behind the open source reactive visual programming language <a href='https://bonsai-rx.org/'>Bonsai</a>, which now powers thousands of experiments around the world. Bonsai is at the centre of a vibrant and growing ecosystem of hardware and software projects in Neuroscience, including Open-Ephys, DeepLabCut, Miniscope, Harp, and Neurophotometrics. ",
      active: true, # Add true to select section
    }
  - {
      name: Integrative Technology Solutions,
      icon: ti-palette,
      description: "Thanks to Bonsai, the open-source visual programming language at the heart of NeuroGEARS, we can offer our services as software and hardware integrators. Our expertise can make it easier to build interactive systems that incorporate a wide range of components that might otherwise be very challenging or impossible to integrate.",
      active: true, # Add true to select section
    }
  - {
      name: Interdisciplinary Research <br/>and Outreach,
      icon: ti-vector,
      description: "NeuroGEARS brings together experts in building virtual and augmented reality systems, interactive installations, autonomous robots, performing arts, and neuroscience research. Our current mission focuses on sustainably funding collaborations that explore methods for field neuroscience with academics, professional artists, and activist communities.",
      active: true, # Add true to select section
    }
  - {
      name: Educational Activism,
      icon: ti-panel,
      description: "At NeuroGEARS, we strive to sustain a network of lifelong learners and optimistic activists passionate about improving the way we teach, grow, and create. To this end, we can offer our services as curriculum developers and teachers with expertise in delivering neuroscience topics through formats that centre a 'hands-on minds-on' approach, collaborative storytelling, whole-body engagement, and age-inclusive classrooms.",
      active: true, # Add true to select section
    }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact
contact-email: contact@neurogears.org
